### ISSUE TITLE
Feature request: Deactivate account

### ISSUE THREAD

**Issue by zcyzcy88** [HelloZeroNet/ZeroID#21]
1. After deactivated, can't reactivate
2. After deactivated, can't use the account to do anything

If someday my privacy key is stolen, try best to reduce data damage via this feature.

**Comment by HelloZeroNet** [comment]
Actually the ZeroID site does not have control over the accounts after it created the certificate signature, so it can't revoke it.
But it can be solved by adding immutable content support: If there is a `locked_until` key present in any content.json, then the client won't accept any updates to that file before the given timestamp value. So you could add `"locked_until": 999999999999999999` to free it ~for ever.
