### ISSUE TITLE
Disallow upper case letter

### ISSUE THREAD

**Issue by 0polar** [HelloZeroNet/ZeroID#24]
Wrong code: https://github.com/HelloZeroNet/ZeroID/blob/master/publisher-http/solution.php#L23
According your rule ["only 0-9 and a-z are allowed in a user name"](https://zeronet.readthedocs.io/en/latest/site_development/cert_authority/), but you still allow upper case letter.

**Comment by HelloZeroNet** [comment]
Thanks for reporting, fixed: https://github.com/HelloZeroNet/ZeroID/commit/67a825bbc08834713bfb297c5605b2482826bcaf
