### ISSUE TITLE
Recover Lost ZeroID 

### ISSUE THREAD

**Issue by KendalS** [HelloZeroNet/ZeroID#8]
After a HDD crash and reinstalling ZeroNet, I no longer have the ZeroID files.  As such, I can no longer access ZeroMail, etc.

Is there a recovery process....?

**Comment by HelloZeroNet** [comment]
No, it's same as for Bitcoin: If you lost your private key, then you lost your identity

**Comment by HelloZeroNet** [comment]
Sorry, it's not possible, sites does not support multiple identities with same username

**Comment by KendalS** [comment]
Again, thanks.

Rgds,
Kendal
